services:
  zonos_server:
    image: ghcr.io/vmenezes599/ct_zonos_server:v0.1.0
    container_name: zonos_server
    labels:
      autoheal: "true"
    gpus: all
    environment:
      PYTHONPATH: /app
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility
      GRADIO_SHARE: "False"
    networks:
      - services_network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "/app/health-check.sh" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
    tmpfs:
      - /tmp:rw,exec,nosuid,size=10g
      - /var/tmp:rw,exec,nosuid,size=10g
    security_opt:
      - no-new-privileges:true

networks:
  services_network:
    name: services_network
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
